package:
    name: python-zpar
    version: "0.9.5"

source:
  path: ../../../python-zpar

build:
    number: {{environ.get('BINSTAR_BUILD', 0)}}
    script:
      - cd $SRC_DIR
      - "{{ PYTHON }} setup.py install"

requirements:
    build:
      - python
      - setuptools
    run:
      - python
      - six

about:
    home: https://github.com/EducationalTestingService/python-zpar
    license: MIT
